name: Build and Publish

on:
  push:
    branches:
      - master  # or your default branch
  pull_request:
    branches:
      - master  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust node version as needed

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build  # Adjust if your build command is different

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
